/**
 * The `vite-plugin-pwa` configuration, as plain data (M3.5). It lives in `src/` rather than inline
 * in `vite.config.ts` so the guarantees below are ASSERTED by a test rather than reviewed by eye —
 * the precache contents decide whether a hoster can rebrand without a rebuild (FR-DEP-04) and
 * whether a stale precache can outlive a deploy.
 *
 * Strategy: **injectManifest** with our own `src/sw/sw.ts`. `generateSW` would emit an untyped,
 * unbundled worker, and the worker has real listeners to carry — M3.6 added `notificationclick`
 * there, type-checked and bundled. (M3.5 expected M3.6 to add `push` and `pushsubscriptionchange`
 * too; it turned out no JMAP server can deliver a Web Push to a browser at all — ADR-010.)
 *
 * With `injectManifest` the plugin's `workbox: {…}` block is IGNORED: `cleanupOutdatedCaches`,
 * `skipWaiting` and `clientsClaim` are OUR calls inside `sw.ts`. Do not add a `workbox:` key here.
 */

import type { VitePWAOptions } from 'vite-plugin-pwa'
import { NEVER_PRECACHE } from './sw-routes'

/**
 * The app-shell precache. `index.html` + the hashed `assets/**` are the only files that may be
 * precached: they are content-addressed, so a new build invalidates them wholesale. Everything a
 * hoster may edit in place ({@link NEVER_PRECACHE}) is runtime-cached instead — see sw-routes.ts.
 */
const PRECACHE_GLOBS: string[] = ['index.html', 'assets/**/*.{js,css}']

/**
 * The entry chunk is ~670 KB raw. Workbox's default ceiling is 2 MiB and it SKIPS an oversized file
 * SILENTLY (a build warning, then a precache that is missing the app), so the ceiling is raised
 * explicitly and generously — the gzipped budget is enforced by size-limit, not here.
 */
const MAX_PRECACHE_FILE_BYTES = 3_000_000

export const pwaOptions: Partial<VitePWAOptions> = {
  strategies: 'injectManifest',
  srcDir: 'src/sw',
  // The SOURCE worker; the plugin bundles it to `sw.js` (SW_FILENAME) at the dist root.
  filename: 'sw.ts',
  registerType: 'prompt',
  // We hand-roll registration (src/pwa/register-sw.ts): no `registerSW.js`, no inline script (the
  // production CSP forbids inline script anyway, NFR-SEC-01), and — decisively — NO auto-update.
  // Activating a new worker under a live tab drops the old precache, so the tab's next lazy route
  // chunk 404s. The user gets a toast and decides.
  injectRegister: false,
  /**
   * The web app manifest is NOT generated by the plugin. It ships as `public/manifest.json` — a
   * plain deployment file next to config.json and theme.css, editable by a white-label hoster with
   * no rebuild (FR-DEP-04) — and index.html links it by hand.
   *
   * This is forced, not preference: whenever the plugin owns the manifest it appends
   * `{url: manifestFilename}` to `additionalManifestEntries`, and workbox-build applies THAT after
   * `manifestTransforms` (workbox-build/lib/transform-manifest.js: "Run additionalManifestEntries
   * last"). A plugin-generated manifest therefore CANNOT be kept out of the precache by any option
   * — its precached copy would shadow the SW's NetworkFirst route and freeze a hoster's rebrand
   * until the next release. `manifest: false` also suppresses the injected <link>, so we write it.
   */
  manifest: false,
  // Never sweep `public/` into the precache — config.json, theme.css, manifest.json and branding/
  // must all stay hoster-editable.
  includeAssets: [],
  includeManifestIcons: false,
  // No service worker in `pnpm dev`: a dev SW caches HMR modules and turns every reload into a puzzle.
  devOptions: { enabled: false },
  // `vitest.config.ts` merges this Vite config, so the plugin is instantiated during `pnpm test`.
  // It must be provably inert there (asserted in pwa-options.test.ts).
  disable: process.env.VITEST === 'true',
  injectManifest: {
    globPatterns: PRECACHE_GLOBS,
    globIgnores: [...NEVER_PRECACHE, '**/*.map'],
    maximumFileSizeToCacheInBytes: MAX_PRECACHE_FILE_BYTES,
  },
}
